Add ignore flag for MM_BIBID

diff --git a/bin/op-get b/bin/op-get
--- a/bin/op-get
+++ b/bin/op-get
@@ -1,7 +1,15 @@
 #!/usr/bin/env bash
 
 usage() {
-    echo "Usage: $0 [-b bibid ] SOURCE_DIR [DEST_DIR=.]"
+    echo "Usage: $0 [-f] [-b bibid ] SOURCE_DIR [DEST_DIR=.]"
+    cat <<EOF
+
+Options:
+        -b bibid  Provide a bibid for the bibid.txt file
+        -f        Force option; for Managed Masters MSS: ignore
+                  BibID or missing BibID from MM_Metadata.xlsx.
+
+EOF
 }
 
 source `dirname $0`/op-functions
@@ -10,7 +18,7 @@ cmd=`basename $0`
 COMMAND=$cmd
 
 ### OPTIONS
-while getopts "hb:" opt; do
+while getopts "hfb:" opt; do
   case $opt in
     h)
       usage
@@ -18,6 +26,9 @@ while getopts "hb:" opt; do
       ;;
     b)
       BIBID=$OPTARG
+      ;;
+    f)
+      FORCE=true
       ;;
     \?)
       echo "ERROR Invalid option: -$OPTARG" >&2
@@ -72,15 +83,25 @@ if is_managed_masters_dir "$SOURCE_DIR"; then
     echo "SOURCE_DIR $SOURCE_DIR is a Managed Masters directory"
     SOURCE_DIR="$SOURCE_DIR/data"
     mm_bibid=`unzip -p "$SOURCE_DIR"/MM_Metadata.xlsx xl/sharedStrings.xml | tr '\r' '\n' | egrep '<t>[0-9]+</t>' | sed 's!.*<t>\([0-9][0-9]*\)</t>.*!\1!'`
+    [[ ! -n "$mm_bibid" ]] && mm_bibid=BIBID_NOT_FOUND
 fi
 
-if [[ -n "$mm_bibid" ]]; then
+if [[ "$FORCE" ]]; then
+    echo "[$cmd] WARNING: Force option selected; ignoring MM_Metadata.xlsx BibID: $mm_bibid"
+    unset $mm_bibid
+elif [[ "$mm_bibid" = "BIBID_NOT_FOUND" ]]; then
+    echo "[$cmd] ERROR: Found MM_Metadata.xlsx but could not detect BibID; please check manually"
+    echo "[$cmd] ERROR: Use force option '-f' to run anyway"
+    exit 1
+elif [[ -n "$mm_bibid" ]]; then
     echo "[$cmd] MM_Metadata.xlsx has BibID: $mm_bibid"
     if [[ -n "$BIBID" ]] ; then
         if [[ "$BIBID" == "$mm_bibid" ]]; then
             echo "[$cmd] OK:    BibID ($BIBID) equals MM_Metadata.xlsx BibID ($mm_bibid)"
         else
-            echo "[$cmd] ERROR: BibID ($BIBID) does not match MM_Metadata.xlsx BibID ($mm_bibid)"
+            echo "[$cmd] ERROR: BibID ($BIBID) does not match MM_Metadata.xlsx BibID ($mm_bibid)" >&2
+            echo "[$cmd] ERROR: Use force option '-f' to run anyway"
+            exit 1
         fi
     else
         echo "[$cmd] WARNING: User did not provide bibid; confirm BibID from MM_Metadata.xlsx: $mm_bibid"
