Add standard script behavior to gen TEI script

diff --git a/bin/op-gen-tei b/bin/op-gen-tei
--- a/bin/op-gen-tei
+++ b/bin/op-gen-tei
@@ -1,7 +1,102 @@
 #!/usr/bin/env bash
 
+
+read -r -d '' HELP <<-'EOF'
+HELP TEXT HERE
+
+EOF
+
+################################################################################
+### TEMPFILES
+# From:
+#   http://stackoverflow.com/questions/430078/shell-script-templates
+# create a default tmp file name
+tmp=${TMPDIR:-/tmp}/prog.$$
+# delete any existing temp files
+trap "rm -f $tmp.?; exit 1" 0 1 2 3 13 15
+# then do
+#   ...real work that creates temp files $tmp.1, $tmp.2, ...
+
+################################################################################
+### CONFIG
+XSL_DIR=$(cd $(dirname $0)/../xsl; pwd)
+PIH_TO_TEI_XSL=$XSL_DIR/pih2tei.xsl
+
+################################################################################
+#### USAGE AND ERRORS
+COMMAND=`basename $0`
+# Load basic functions; primarily messaging functions
+# Rename file name here to match actual functions
+source "`dirname $0`/op-functions"
+
+# Note that LOGFILE is used by functions for log commands: log_message,
+# log_warning, log_error, etc.
+#
+# replace log file with another value if you want
+LOGFILE=LOG_${COMMAND}_`tstamp`.log
+
+usage() {
+   echo "Usage: $cmd [OPTIONS] XML"
+   echo ""
+   echo "Given a Penn in Hand XML file generate OPenn TEI."
+   echo ""
+   echo "OPTIONS"
+   echo "      -t    Optional XSL [DEFAULT=$PIH_TO_TEI_XSL]"
+   echo ""
+}
+
+print_help() {
+  echo "$HELP"
+}
+
+
+################################################################################
+### OPTIONS
+while getopts "ht:" opt; do
+  case $opt in
+    h)
+      usage
+      print_help
+      exit 1
+      ;;
+    t)
+      PIH_TO_TEI_XSL=$OPTARG
+      ;;
+    \?)
+      echo "ERROR Invalid option: -$OPTARG" >&2
+      echo ""
+      usage
+      exit 1
+      ;;
+  esac
+done
+
+shift $((OPTIND-1))
+
+
+################################################################################
+### THESCRIPT
+
+XML="$1"
+if file_exists "$XML" XML ; then
+  message "Using XML: $XML" >&2
+else
+  error "Error finding XML"
+fi
+
+message "Using XSL: $PIH_TO_TEI_XSL" >&2
+
+# TODO: Figure out a more flexible way to handle classpath
 LIB_DIR=$HOME/Java/SaxonHE9-5-1-5J
 CLASSPATH=$CLASSPATH:$LIB_DIR/saxon9he.jar
 
-java -cp $CLASSPATH net.sf.saxon.Transform -s:$1 -xsl:$2
+java -cp $CLASSPATH net.sf.saxon.Transform -s:$XML -xsl:$PIH_TO_TEI_XSL
+
+
+################################################################################
+### EXIT
+# http://stackoverflow.com/questions/430078/shell-script-templates
+rm -f $tmp.?
+trap 0
+exit 0
 
