Clean up test comments

diff --git a/test/shunit_helper b/test/shunit_helper
--- a/test/shunit_helper
+++ b/test/shunit_helper
@@ -121,6 +121,54 @@ insert_document() {
     mysql -u $OPENN_DB_USER $OPENN_DB_NAME -e "$sql"
 }
 
+get_repository_id() {
+    gci_tag=${1?get_repository_id - tag required}
+    gci_id=`mysql --batch --skip-column-names -u openn openn -e "select id from openn_repository where tag = '$gci_tag'"`
+    [[ -z "$gci_id" ]] && return 1
+    echo $gci_id
+    return 0
+}
+
+get_repository_folder() {
+    gcf_id=`get_repository_id $1`
+    [[ -z "$gcf_id" ]] && return 1
+    printf "%04d\n" $gcf_id
+    return 0
+}
+
+get_staging_destination() {
+    gsd_folder=`get_repository_folder $1`
+    gsd_source_dir=$2
+    [[ -z "$gsd_folder" ]] && return 1
+    [[ -z "$gsd_source_dir" ]] && return 1
+    echo $STAGING_DATA_DIR/$gsd_folder/`basename $gsd_source_dir`
+    return 0
+}
+
+touch_dummy_files() {
+    tdf_dest_dir=$1
+    tdf_file_list=$2
+    if [[ -z "$tdf_dest_dir" ]] || [[ ! -d $tdf_dest_dir ]]; then
+        echo "[create_dummy_files] Directory not found: '$tdf_dest_dir'; quitting"
+        exit 1
+    fi
+    for x in ${!tdf_file_list}; do
+        touch "$tdf_dest_dir/$x"
+    done
+}
+
+create_dummy_files() {
+    cdf_dest_dir=$1
+    cdf_file_list=$2
+    if [[ -z "$cdf_dest_dir" ]] || [[ ! -d $cdf_dest_dir ]]; then
+        echo "[create_dummy_files] Directory not found: '$cdf_dest_dir'; quitting"
+        exit 1
+    fi
+    for x in ${!cdf_file_list}; do
+        cp $TEMPLATE_TIFF "$cdf_dest_dir/$x"
+    done
+}
+
 # Usage: save_and_open FILE [APP]
 #
 # Copy the file to TMPDIR and open; optionally specifying the application.
